language: android
dist: trusty
sudo: required
jdk: oraclejdk8

env:
   global:
      - ANDROID_API_LEVEL=30
      - EMULATOR_API_LEVEL=24
      - ANDROID_BUILD_TOOLS_VERSION=30.0.2
      - ANDROID_ABI=armeabi-v7a # x86 requires HAXM and it's not supported by travis (https://github.com/travis-ci/travis-ci/issues/1419)
      - ADB_INSTALL_TIMEOUT=8 # in minutes (2 minutes by default)

android: 
   components:
      - tools
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
      - extra-google-google_play_services
      - extra-android-m2repository
      - extra-google-m2repository
   licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+

#optional, use it if only you haven't give permission yet.
#before_install:
#   - chmod +x gradlew
script:
   - ./gradlew build
before_install:
- chmod +x gradlew
